version: '3'
services:
  playground-web-db:
    image: mongo:latest
    container_name: mymongodb
    volumes:
      - mongodata:/data/db
    networks:
      - node-network
    ports:
      - 23456:27017
  playground-web-frontend:
    image: spade0412/car_rental_frontend:latest
    container_name: frontend_cont
    environment:
      PORT: 3000
      PROXY_API: http://car_rental:5000/
    restart: always
    ports:
      - 3000:3000
  playground-web-backend:
    image: spade0412/car_rental_backend:latest
    container_name: backend_cont
    environment:
      URI: mongodb://mymongodb:23456
    restart: always
    depends_on:
      - playground-web-db
    volumes:
      - .:/src
    networks:
      - node-network
    ports:
      - 5000:5000

volumes:
  mongodata:

networks:
  node-network:
    driver: bridge