version: '3'
services:
  mymongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    networks:
      - node-network
    ports:
      - 23456:27017
  frontend_cont:
    image: spade0412/car_rental_frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://car_rental:5000/
    restart: always
    ports:
      - 3000:3000
  backend_cont:
    image: spade0412/car_rental_backend:latest
    environment:
      URI: mongodb://mymongodb:27017
    restart: always
    depends_on:
      - mymongodb
    volumes:
      - .:/src
    networks:
      - node-network
    ports:
      - 5000:5000

volumes:
  mongodata:

networks:
  node-network:
    driver: bridge