---
- name: Deploy Docker Images
  hosts: all

  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
      
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ../docker-compose.yml
        dest: ./

    - name: Pull the Docker images specifed in docker-compose
      shell: 
        cmd: docker-compose pull
        chdir: ./

    - name: Pull the Docker images specifed in docker-compose
      command: touch .env

    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d

    - name: Prune the dangling Docker images
      command: docker image prune --force